# NumPy 

NumPy is a Linear Algebra Library for Python.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional).

Numpy is also incredibly fast, as it has bindings to C libraries.

For easy installing Numpy:
```bash 
sudo pip install numpy
```


### NumPy array 



In [30]:
import numpy as np 

In [53]:
a = [1,2,3]

In [54]:
a

[1, 2, 3]

In [55]:
b = np.array(a)

In [74]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### zeros , ones and eye


###### np.zeros

Return a new array of given shape and type, filled with zeros.

In [84]:
np.zeros(2, dtype=float)

array([ 0.,  0.])

In [85]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

###### ones
Return a new array of given shape and type, filled with ones.

In [88]:
np.ones(3, )

array([ 1.,  1.,  1.])

###### eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [106]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

###### linspace

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [121]:
np.linspace(1, 11, 3)

array([  1.,   6.,  11.])

### Random number and matrix

###### rand

Random values in a given shape.

In [129]:
np.random.rand(2)

array([ 0.82377024,  0.40424258])

In [133]:
np.random.rand(2,3,4)

array([[[ 0.64291577,  0.87234365,  0.16078424,  0.82920449],
        [ 0.01633982,  0.87048537,  0.15522803,  0.06318826],
        [ 0.15905419,  0.53776075,  0.23650835,  0.46665814]],

       [[ 0.33255144,  0.38405888,  0.81762695,  0.73669923],
        [ 0.44528786,  0.9067376 ,  0.49499621,  0.592627  ],
        [ 0.55964688,  0.71899107,  0.28686233,  0.03277708]]])

###### randn

Return a sample (or samples) from the "standard normal" distribution.

- andom.standard_normal    Similar, but takes a tuple as its argument. 


In [146]:
np.random.randn(2,3)

array([[-1.64491013, -0.62652185,  0.44303439],
       [-1.53718651, -0.4184097 , -0.97852363]])

###### random

Return random floats in the half-open interval [0.0, 1.0).

In [148]:
np.random.random()

0.9930578739263191

###### randint


Return n random integers (by default one integer) from low (inclusive) to high (exclusive).

In [151]:
np.random.randint(1,50,10)

array([32, 40, 34, 10, 38, 31, 35, 33, 18, 45])

In [153]:
np.random.randint(1,40)

20

# add 'reshape' 'shape' 'min' 'max' 'argmin' 'argmax' 'dtype' 'shallow' 'copy' 'and' 'deep' 'copy' and 'broadcastion in python'

### Why we use use Numpy ?

##### because it's so fast 

 see it 

In [67]:
from time import time
c = 0
tic = time()
for i in range(len(a)):
    c += a[i] * a[i]
print ('output:', c)
tak = time()

print('multiply 2 matrix with loop: ', tak - tic)

tic = time()
print('output:', np.dot(b, b))
tak = time()

print('multiply 2 matrix with numpy func: ', tak - tic)

output: 14
multiply 2 matrix with loop:  0.0007216930389404297
output: 14
multiply 2 matrix with numpy func:  0.00027680397033691406
