# NumPy 

NumPy is a Linear Algebra Library for Python.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional).

Numpy is also incredibly fast, as it has bindings to C libraries.

For easy installing Numpy:
```bash 
sudo pip install numpy
```


### NumPy array 



In [1]:
import numpy as np 

In [2]:
a = [1,2,3]

In [3]:
a

[1, 2, 3]

In [4]:
b = np.array(a)

In [5]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### zeros , ones and eye


###### np.zeros

Return a new array of given shape and type, filled with zeros.

In [7]:
np.zeros(2, dtype=float)

array([ 0.,  0.])

In [8]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

###### ones
Return a new array of given shape and type, filled with ones.

In [9]:
np.ones(3, )

array([ 1.,  1.,  1.])

###### eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

###### linspace

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [11]:
np.linspace(1, 11, 3)

array([  1.,   6.,  11.])

### Random number and matrix

###### rand

Random values in a given shape.

In [12]:
np.random.rand(2)

array([ 0.65511284,  0.13989139])

In [13]:
np.random.rand(2,3,4)

array([[[ 0.17730238,  0.0949157 ,  0.78499115,  0.38984114],
        [ 0.97621367,  0.58412221,  0.36182271,  0.81934748],
        [ 0.57024044,  0.22106029,  0.60203295,  0.05562824]],

       [[ 0.23103561,  0.87051872,  0.62952171,  0.0597917 ],
        [ 0.75766258,  0.74034135,  0.13089593,  0.55657907],
        [ 0.40384534,  0.76685131,  0.19206323,  0.607362  ]]])

###### randn

Return a sample (or samples) from the "standard normal" distribution.

- andom.standard_normal    Similar, but takes a tuple as its argument. 


In [14]:
np.random.randn(2,3)

array([[ 0.39799936,  0.59389898, -2.23716852],
       [-0.13668975,  0.48120318,  0.14194033]])

###### random

Return random floats in the half-open interval [0.0, 1.0).

In [15]:
np.random.random()

0.8870666340323976

###### randint


Return n random integers (by default one integer) from low (inclusive) to high (exclusive).

In [16]:
np.random.randint(1,50,10)

array([ 3, 30, 24,  8, 17, 17, 18, 30, 39,  3])

In [17]:
np.random.randint(1,40)

5

#### Shape and Reshape

###### shape return the shape of data and reshape returns an array containing the same data with a new shape

In [29]:
zero = np.zeros([3,4])
print(zero , '   ' ,'shape of a :' , zero.shape)
zero = zero.reshape([2,6])
prin
print(zero)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]     shape of a : (3, 4)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


### min max argmin argmax mean 

In [41]:
numbers = np.random.randint(1,100, 10)
print(numbers)
print('max is :', numbers.max())
print('index of max :', numbers.argmax())
print('min is :', numbers.min())
print('index of min :', numbers.argmin())
print('mean :', numbers.mean())

[ 7 29 45 69 62 26 51 67 50 87]
max is : 87
index of max : 9
min is : 7
index of min : 0
mean : 49.3


##### dtype

In [44]:
numbers.dtype

dtype('int64')

# No copy & Shallow copy & Deep copy


* ### No copy 
   ###### Simple assignments make no copy of array objects or of their data.

In [88]:
number = np.arange(0,20)
number2 = number 
print (number is number2 , id(number), id(number2))
print(number)
number2.shape = (4,5)
print(number)

True 140658979663344 140658979663344
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


* ### Shallow copy
 #### Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [139]:
number = np.arange(0,20)
number2 = number.view()
print (number is number2 , id(number), id(number2))
print ('check id of list number :',id(number[0]), id(number2[0]), id(number[0]) == id(number2[0]))

False 140658979759088 140658979758848
check id of list number : 140658979632784 140658979632784 True


In [140]:
number2.shape = (5,4)
print('number2 shape:', number2.shape,'\nnumber shape:', number.shape)

number2 shape: (5, 4) 
number shape: (20,)


In [141]:
print('befor:', number)
number2[0][0] = 2222
print()
print('after:', number)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [2222    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19]


* ### Deep copy 
 #### The copy method makes a complete copy of the array and its data.

In [151]:
number = np.arange(0,20)
number2 = number.copy()
print (number is number2 , id(number), id(number2))
print ('check id of list number :',id(number[0]), id(number2[0]), id(number[0]) == id(number2[0]))

False 140658979761728 140658979761648
check id of list number : 140658979633072 140658979633072 True


In [152]:
eprint('befor:', number)
number2[0] = 2222
print()
print('after:', number)
print(number2)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2222    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19]


# to do
## operation broadcasting linear_algebra and id bug  

### Why we use use Numpy ?

##### because it's so fast 

 see it 

In [ ]:
from time import time
c = 0
tic = time()
for i in range(len(a)):
    c += a[i] * a[i]
print ('output:', c)
tak = time()

print('multiply 2 matrix with loop: ', tak - tic)

tic = time()
print('output:', np.dot(b, b))
tak = time()

print('multiply 2 matrix with numpy func: ', tak - tic)