# NumPy 

NumPy is a Linear Algebra Library for Python.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional).

Numpy is also incredibly fast, as it has bindings to C libraries.

For easy installing Numpy:
```bash 
sudo pip install numpy
```


### NumPy array 



In [1]:
import numpy as np 

a = [1,2,3]

a

[1, 2, 3]

In [2]:
b = np.array(a)
b

array([1, 2, 3])

In [3]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### zeros , ones and eye


###### np.zeros

Return a new array of given shape and type, filled with zeros.

In [5]:
np.zeros(2, dtype=float)

array([ 0.,  0.])

In [6]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

###### ones
Return a new array of given shape and type, filled with ones.

In [7]:
np.ones(3, )

array([ 1.,  1.,  1.])

###### eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [8]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

###### linspace

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [9]:
np.linspace(1, 11, 3)

array([  1.,   6.,  11.])

### Random number and matrix

###### rand

Random values in a given shape.

In [10]:
np.random.rand(2)

array([ 0.09950408,  0.34058237])

In [11]:
np.random.rand(2,3,4)

array([[[ 0.68282604,  0.65598576,  0.81996482,  0.07963194],
        [ 0.81410601,  0.89702462,  0.08894526,  0.1307713 ],
        [ 0.86223315,  0.31796219,  0.18792348,  0.1654565 ]],

       [[ 0.04674239,  0.45483823,  0.80281198,  0.91478186],
        [ 0.83474728,  0.25597002,  0.73895168,  0.51091939],
        [ 0.95043172,  0.66900036,  0.30389842,  0.32728317]]])

###### randn

Return a sample (or samples) from the "standard normal" distribution.

- andom.standard_normal    Similar, but takes a tuple as its argument. 


In [12]:
np.random.randn(2,3)

array([[ 0.01894578, -1.69022417,  0.00993446],
       [-0.30764603, -1.50879482,  1.41659491]])

###### random

Return random floats in the half-open interval [0.0, 1.0).

In [13]:
np.random.random()

0.6620273698371913

###### randint


Return n random integers (by default one integer) from low (inclusive) to high (exclusive).

In [14]:
np.random.randint(1,50,10)

array([15, 35,  8, 25, 45,  3, 46, 33, 13, 48])

In [15]:
np.random.randint(1,40)

29

#### Shape and Reshape

###### shape return the shape of data and reshape returns an array containing the same data with a new shape

In [16]:
zero = np.zeros([3,4])
print(zero , '   ' ,'shape of a :' , zero.shape)
zero = zero.reshape([2,6])
print()
print(zero)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]     shape of a : (3, 4)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


## Basic Operation

#### Element wise product and matrix product

In [17]:
number = np.array([[1,2,],[3,4]])
number2 = np.array([[1,3],[2,1]])

print('element wise product :\n',number * number2 )
print('matrix product :\n',number.dot(number2))     ## also can use : np.dot(number, number2)

element wise product :
 [[1 6]
 [6 4]]
matrix product :
 [[ 5  5]
 [11 13]]


### min max argmin argmax mean 

In [18]:
numbers = np.random.randint(1,100, 10)
print(numbers)
print('max is :', numbers.max())
print('index of max :', numbers.argmax())
print('min is :', numbers.min())
print('index of min :', numbers.argmin())
print('mean :', numbers.mean())

[71 32 84 61 75 89 47 62 38 56]
max is : 89
index of max : 5
min is : 32
index of min : 1
mean : 61.5


## Universal function 

numpy also has some funtion for mathmatical operation like exp, log, sqrt, abs and etc .

for find more function click [here](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) 


In [19]:
number = np.arange(1,10).reshape(3,3)
print(number)
print()
print('exp:\n', np.exp(number))
print()
print('sqrt:\n',np.sqrt(number))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

exp:
 [[  2.71828183e+00   7.38905610e+00   2.00855369e+01]
 [  5.45981500e+01   1.48413159e+02   4.03428793e+02]
 [  1.09663316e+03   2.98095799e+03   8.10308393e+03]]

sqrt:
 [[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]
 [ 2.64575131  2.82842712  3.        ]]


##### dtype

In [20]:
numbers.dtype

dtype('int64')

# No copy & Shallow copy & Deep copy


* ### No copy 
   ###### Simple assignments make no copy of array objects or of their data.

In [21]:
number = np.arange(0,20)
number2 = number 
print (number is number2 , id(number), id(number2))
print(number)
number2.shape = (4,5)
print(number)

True 140417983235296 140417983235296
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


* ### Shallow copy

  Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [22]:
number = np.arange(0,20)
number2 = number.view()
print (number is number2 , id(number), id(number2))

False 140417983234496 140417983235616


In [23]:
number2.shape = (5,4)
print('number2 shape:', number2.shape,'\nnumber shape:', number.shape)

number2 shape: (5, 4) 
number shape: (20,)


In [24]:
print('befor:', number)
number2[0][0] = 2222
print()
print('after:', number)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [2222    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19]


* ### Deep copy 

  The copy method makes a complete copy of the array and its data.

In [25]:
number = np.arange(0,20)
number2 = number.copy()
print (number is number2 , id(number), id(number2))


False 140417983236576 140417983236896


In [26]:
print('befor:', number)
number2[0] = 10
print()
print('after:', number)
print()
print('number2:',number2)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

number2: [10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Broadcating

 ###### One of important concept to understand numpy is Broadcasting 
 It's very useful for performancing mathmaica operation beetween arrays of different shape.
         

In [27]:
number = np.arange(1,11)
num = 2 
print(' number =', number)
print('\n number .* num =',number * num)

 number = [ 1  2  3  4  5  6  7  8  9 10]

 number .* num = [ 2  4  6  8 10 12 14 16 18 20]


In [28]:
number = np.arange(1,10).reshape(3,3)
number2 = np.arange(1,4).reshape(1,3)
number * number2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [29]:
number = np.array([1,2,3])
print('number =', number)
print('\nnumber =', number + 100)

number = [1 2 3]

number = [101 102 103]


In [30]:
number = np.arange(1,10).reshape(3,3)
number2 = np.arange(1,4)
print('number: \n', number)
add = number + number2 
print()
print('number2: \n ', number2)
print()
print('add: \n', add)

number: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

number2: 
  [1 2 3]

add: 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## If you still doubt Why we use Python and NumPy see it. 😉
 

In [31]:
from time import time
a = np.random.rand(8000000, 1)
c = 0
tic = time()
for i in range(len(a)):
    c +=(a[i][0] * a[i][0])
          
print ('output1:', c)
tak = time()

print('multiply 2 matrix with loop: ', tak - tic)

tic = time()
print('output2:', np.dot(a.T, a))
tak = time()


print('multiply 2 matrix with numpy func: ', tak - tic)

output1: 2665562.66419
multiply 2 matrix with loop:  5.04582667350769
output2: [[ 2665562.6641903]]
multiply 2 matrix with numpy func:  0.003988981246948242


### I tried to write essential things in numpy that you can start to code and enjpy it but there are many function  that i don't write in this book if you neet more informatino click [here](https://docs.scipy.org/doc/numpy-dev/reference/routines.html#routines)