# A Crash Course in Python for Scientists

### Why Python?
Python is the programming language of choice for many scientists to a large degree because it offers a great deal of power to analyze and model scientific data with relatively little overhead in terms of learning, installation or development time. It is a language you can pick up in a weekend, and use for the rest of one's life.


Please note, is not meant to be a comprehensive overview of Python or programming in general, if you have no programming experience,I suggest to read [Python for You and Me.](https://733amir.github.io/python-for-you-and-me/)

#### Topic
* Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets
* Comparison Operators
* if,elif, else Statements
* for Loops
* while Loops
* range()
* list comprehension
* map and filter
* functions
* lambda expressions
* map and filter
____

## Data types

### Numbers and Arithmetics

In [1]:
2 + 2

4

In [2]:
2 * 3

6

In [3]:
1 / 2 

0.5

In [4]:
7 // 2

3

In [5]:
4 ** 3

64

In [6]:
23 % 4

3

In [7]:
var = 2 
var2 = 54

In [8]:
var3 = var2 - var

In [9]:
var3

52

### String 

In [10]:
'Hello world' 

'Hello world'

In [11]:
"Hello world"

'Hello world'

### Print

In [12]:
print('Hello world')

Hello world


In [13]:
name = 'sadegh'
course = 'Machine learning'

In [14]:
print('My name is {} this is a {} course'.format(name,course))

My name is sadegh this is a Machine learning course


In [15]:
print('My name is {myname} this is a {name_course} course'.format(name_course = course, myname = name))

My name is sadegh this is a Machine learning course


### Lists

In [16]:
[1, 2, 3]

[1, 2, 3]

In [17]:
[1 , [3, 4], 'hello :)']

[1, [3, 4], 'hello :)']

In [18]:
myList = [1 ,2 ,3, 4, 5, 6]

In [19]:
myList.append(12)

In [20]:
myList

[1, 2, 3, 4, 5, 6, 12]

In [21]:
myList[2] 

3

In [22]:
myList[1:3]  

[2, 3]

In [23]:
myList [1:]

[2, 3, 4, 5, 6, 12]

In [24]:
myList[0:5:2]

[1, 3, 5]

In [25]:
myList[-1]

12

In [26]:
myList[0]

1

In [27]:
myList[0] = 'wow'

In [28]:
myList

['wow', 2, 3, 4, 5, 6, 12]

In [29]:
myList = [[[1, 2 ,3], [4, 5, 6], [7, 8, 9]], [[-1, -2, -3], [-4, -5, -6], [-7, -8 , -9]]]

In [30]:
myList[0][2][2]

9

In [31]:
np.array(myList)

NameError: name 'np' is not defined

### Dictionaries

In [32]:
dictinary = {'key1':'item1','key2':'item2'} 

In [33]:
dictinary

{'key1': 'item1', 'key2': 'item2'}

In [34]:
dictinary['key1']

'item1'

### Tuples

In [35]:
t = (1, 2, 3)

In [36]:
t[0]

1

In [37]:
t[0] = 5

TypeError: 'tuple' object does not support item assignment

## Comparison Operators ## Logic Operators
 bigger than, les than, equal and ,,,
 
 and, or 

## if,elif, else Statements

In [38]:
if 23 < 34:
    print('hello')

hello


In [39]:
if 5 < 2:
    print('first')
else:
    print('second')

second


In [40]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('second')
else:
    print('third')

second


## for Loops

In [41]:
seq = ['hello', 'python', 'good']

In [42]:
for i in seq:
    print(i)

hello
python
good


In [43]:
seq = [1, 2, 3, 4, 5]

In [44]:
for i in seq:
    print (i ** 2)

1
4
9
16
25


### range()

In [45]:
range(5)

range(0, 5)

In [46]:
list(range(5))

[0, 1, 2, 3, 4]

In [47]:
for i in range(2,5):
    print(i)

2
3
4


## while Loops

In [48]:
i = 1
while i < 5:
    print('number i is: {}'.format(i))
    i += 1

number i is: 1
number i is: 2
number i is: 3
number i is: 4


## list comprehension

In [49]:
x = [1, 2, 3, 4]

In [50]:
output = list()
#output = []
for i in x :
    output.append(i + 2)
output

[3, 4, 5, 6]

In [51]:
[i + 2 for i in x]

[3, 4, 5, 6]

## functions



In [52]:
def func(param1):
    print(param1)


In [53]:
func(param1='hello')

hello


In [54]:
def func2(number):
    return number * 2

In [55]:
func2(2)

4


## map and filter


In [56]:
seq = [1,2,3,4,5]

In [57]:
map(func2,seq)

In [58]:

list(map(func2,seq))


[2, 4, 6, 8, 10]

### lambda expressions

In [59]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [60]:
filter(lambda item: item%2 == 0,seq)

In [61]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

## Other


# NumPy 

NumPy is a Linear Algebra Library for Python.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional).

Numpy is also incredibly fast, as it has bindings to C libraries.

For easy installing Numpy:
```bash 
sudo pip install numpy
```


### NumPy array 



In [62]:
import numpy as np 

a = [1,2,3]

a

[1, 2, 3]

In [63]:
b = np.array(a)
b

array([1, 2, 3])

In [64]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### zeros , ones and eye


###### np.zeros

Return a new array of given shape and type, filled with zeros.

In [66]:
np.zeros(2, dtype=float)

array([ 0.,  0.])

In [67]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

###### ones
Return a new array of given shape and type, filled with ones.

In [68]:
np.ones(3, )

array([ 1.,  1.,  1.])

###### eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [69]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

###### linspace

Returns num evenly spaced samples, calculated over the interval [start, stop].

In [70]:
np.linspace(1, 11, 3)

array([  1.,   6.,  11.])

### Random number and matrix

###### rand

Random values in a given shape.

In [71]:
np.random.rand(2)

array([ 0.09162689,  0.54042187])

In [72]:
np.random.rand(2,3,4)

array([[[ 0.91397668,  0.18832234,  0.49012256,  0.27405501],
        [ 0.55479732,  0.0532756 ,  0.17655563,  0.48706271],
        [ 0.63756364,  0.11926936,  0.61915148,  0.40626583]],

       [[ 0.59686018,  0.94793463,  0.73918299,  0.28100002],
        [ 0.80613957,  0.72738641,  0.44665167,  0.77220101],
        [ 0.77838283,  0.32272713,  0.21900333,  0.89212666]]])

###### randn

Return a sample (or samples) from the "standard normal" distribution.

- andom.standard_normal    Similar, but takes a tuple as its argument. 


In [73]:
np.random.randn(2,3)

array([[-0.88513115, -0.27033797, -1.33864202],
       [-0.24806366, -1.24631343, -1.27609882]])

###### random

Return random floats in the half-open interval [0.0, 1.0).

In [74]:
np.random.random()

0.9760034267568325

###### randint


Return n random integers (by default one integer) from low (inclusive) to high (exclusive).

In [75]:
np.random.randint(1,50,10)

array([29, 15, 40, 47, 43, 23, 48,  3, 24,  4])

In [76]:
np.random.randint(1,40)

7

#### Shape and Reshape

###### shape return the shape of data and reshape returns an array containing the same data with a new shape

In [77]:
zero = np.zeros([3,4])
print(zero , '   ' ,'shape of a :' , zero.shape)
zero = zero.reshape([2,6])
print()
print(zero)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]     shape of a : (3, 4)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


## Basic Operation

#### Element wise product and matrix product

In [78]:
number = np.array([[1,2,],[3,4]])
number2 = np.array([[1,3],[2,1]])

print('element wise product :\n',number * number2 )
print('matrix product :\n',number.dot(number2))     ## also can use : np.dot(number, number2)

element wise product :
 [[1 6]
 [6 4]]
matrix product :
 [[ 5  5]
 [11 13]]


### min max argmin argmax mean 

In [79]:
numbers = np.random.randint(1,100, 10)
print(numbers)
print('max is :', numbers.max())
print('index of max :', numbers.argmax())
print('min is :', numbers.min())
print('index of min :', numbers.argmin())
print('mean :', numbers.mean())

[84 80 43  7 77 50 70 66 98 93]
max is : 98
index of max : 8
min is : 7
index of min : 3
mean : 66.8


## Universal function 

numpy also has some funtion for mathmatical operation like exp, log, sqrt, abs and etc .

for find more function click [here](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) 


In [80]:
number = np.arange(1,10).reshape(3,3)
print(number)
print()
print('exp:\n', np.exp(number))
print()
print('sqrt:\n',np.sqrt(number))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

exp:
 [[  2.71828183e+00   7.38905610e+00   2.00855369e+01]
 [  5.45981500e+01   1.48413159e+02   4.03428793e+02]
 [  1.09663316e+03   2.98095799e+03   8.10308393e+03]]

sqrt:
 [[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]
 [ 2.64575131  2.82842712  3.        ]]


##### dtype

In [81]:
numbers.dtype

dtype('int64')

# No copy & Shallow copy & Deep copy


* ### No copy 
   ###### Simple assignments make no copy of array objects or of their data.

In [82]:
number = np.arange(0,20)
number2 = number 
print (number is number2 , id(number), id(number2))
print(number)
number2.shape = (4,5)
print(number)

True 140342888521120 140342888521120
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


* ### Shallow copy

  Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [83]:
number = np.arange(0,20)
number2 = number.view()
print (number is number2 , id(number), id(number2))

False 140342888521360 140342888521440


In [84]:
number2.shape = (5,4)
print('number2 shape:', number2.shape,'\nnumber shape:', number.shape)

number2 shape: (5, 4) 
number shape: (20,)


In [85]:
print('befor:', number)
number2[0][0] = 2222
print()
print('after:', number)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [2222    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19]


* ### Deep copy 

  The copy method makes a complete copy of the array and its data.

In [86]:
number = np.arange(0,20)
number2 = number.copy()
print (number is number2 , id(number), id(number2))


False 140342557823184 140342557824144


In [87]:
print('befor:', number)
number2[0] = 10
print()
print('after:', number)
print()
print('number2:',number2)

befor: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

after: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

number2: [10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Broadcating

 ###### One of important concept to understand numpy is Broadcasting 
 It's very useful for performancing mathmaica operation beetween arrays of different shape.
         

In [88]:
number = np.arange(1,11)
num = 2 
print(' number =', number)
print('\n number .* num =',number * num)

 number = [ 1  2  3  4  5  6  7  8  9 10]

 number .* num = [ 2  4  6  8 10 12 14 16 18 20]


In [89]:
number = np.arange(1,10).reshape(3,3)
number2 = np.arange(1,4).reshape(1,3)
number * number2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [90]:
number = np.array([1,2,3])
print('number =', number)
print('\nnumber =', number + 100)

number = [1 2 3]

number = [101 102 103]


In [91]:
number = np.arange(1,10).reshape(3,3)
number2 = np.arange(1,4)
print('number: \n', number)
add = number + number2 
print()
print('number2: \n ', number2)
print()
print('add: \n', add)

number: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

number2: 
  [1 2 3]

add: 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## If you still doubt Why we use Python and NumPy see it. 😉
 

In [92]:
from time import time
a = np.random.rand(8000000, 1)
c = 0
tic = time()
for i in range(len(a)):
    c +=(a[i][0] * a[i][0])
          
print ('output1:', c)
tak = time()

print('multiply 2 matrix with loop: ', tak - tic)

tic = time()
print('output2:', np.dot(a.T, a))
tak = time()


print('multiply 2 matrix with numpy func: ', tak - tic)

output1: 2665933.69284
multiply 2 matrix with loop:  4.968470335006714
output2: [[ 2665933.69283681]]
multiply 2 matrix with numpy func:  0.005457639694213867


### I tried to write essential things in numpy that you can start to code and enjpy it but there are many function  that i don't write in this book if you neet more informatino click [here](https://docs.scipy.org/doc/numpy-dev/reference/routines.html#routines)

## Pandas 
 pandas is an open source library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.
 
 For easy installing Pandas
```bash 
sudo pip3 install pandas
```




In [159]:
import pandas as pd 

## Series 

In [161]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [162]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [163]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [164]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## Dataframe 
  Two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). Arithmetic operations align on both row and column labels. Can be thought of as a dict-like container for Series objects. The primary pandas data structure

In [94]:
dataframe = pd.DataFrame(np.random.randn(5,4),columns='A B C D'.split())

In [95]:
dataframe.head()

A         B         C         D
0 -0.437053  1.705375  0.325408 -0.445319
1  1.726463 -1.715308 -0.031324  0.582243
2  1.432421 -1.363992 -0.885771 -0.468531
3  1.988862  0.302918 -0.607677  0.256464
4 -1.203833  0.573521  0.330387  0.424845

### Selection

In [96]:
dataframe['A']

0   -0.437053
1    1.726463
2    1.432421
3    1.988862
4   -1.203833
Name: A, dtype: float64

In [97]:
dataframe[['A', 'D']]

A         D
0 -0.437053 -0.445319
1  1.726463  0.582243
2  1.432421 -0.468531
3  1.988862  0.256464
4 -1.203833  0.424845

### creating new column  

In [98]:
dataframe['E'] = dataframe['A'] + dataframe['B']

In [99]:
dataframe

A         B         C         D         E
0 -0.437053  1.705375  0.325408 -0.445319  1.268322
1  1.726463 -1.715308 -0.031324  0.582243  0.011155
2  1.432421 -1.363992 -0.885771 -0.468531  0.068429
3  1.988862  0.302918 -0.607677  0.256464  2.291780
4 -1.203833  0.573521  0.330387  0.424845 -0.630313

### removing a column

In [100]:
dataframe.drop('E', axis=1)

A         B         C         D
0 -0.437053  1.705375  0.325408 -0.445319
1  1.726463 -1.715308 -0.031324  0.582243
2  1.432421 -1.363992 -0.885771 -0.468531
3  1.988862  0.302918 -0.607677  0.256464
4 -1.203833  0.573521  0.330387  0.424845

In [101]:
dataframe

A         B         C         D         E
0 -0.437053  1.705375  0.325408 -0.445319  1.268322
1  1.726463 -1.715308 -0.031324  0.582243  0.011155
2  1.432421 -1.363992 -0.885771 -0.468531  0.068429
3  1.988862  0.302918 -0.607677  0.256464  2.291780
4 -1.203833  0.573521  0.330387  0.424845 -0.630313

In [102]:
dataframe.drop('E', axis=1, inplace=True)
dataframe

A         B         C         D
0 -0.437053  1.705375  0.325408 -0.445319
1  1.726463 -1.715308 -0.031324  0.582243
2  1.432421 -1.363992 -0.885771 -0.468531
3  1.988862  0.302918 -0.607677  0.256464
4 -1.203833  0.573521  0.330387  0.424845

### Selcting row

In [103]:
dataframe.loc[0]

A   -0.437053
B    1.705375
C    0.325408
D   -0.445319
Name: 0, dtype: float64

In [104]:
dataframe.iloc[0]

A   -0.437053
B    1.705375
C    0.325408
D   -0.445319
Name: 0, dtype: float64

In [105]:
dataframe.loc[0 , 'A']

-0.43705279465583358

In [106]:
dataframe.loc[[0,2],['A', 'C']]

A         C
0 -0.437053  0.325408
2  1.432421 -0.885771

### Conditional Selection


In [107]:
dataframe > 0.3

A      B      C      D
0  False   True   True  False
1   True  False  False   True
2   True  False  False  False
3   True   True  False  False
4  False   True   True   True

In [108]:
dataframe[dataframe > 0.3 ]

A         B         C         D
0       NaN  1.705375  0.325408       NaN
1  1.726463       NaN       NaN  0.582243
2  1.432421       NaN       NaN       NaN
3  1.988862  0.302918       NaN       NaN
4       NaN  0.573521  0.330387  0.424845

In [109]:
dataframe[dataframe['A']>0.3]

A         B         C         D
1  1.726463 -1.715308 -0.031324  0.582243
2  1.432421 -1.363992 -0.885771 -0.468531
3  1.988862  0.302918 -0.607677  0.256464

In [110]:
dataframe[dataframe['A']>0.3]['B']

1   -1.715308
2   -1.363992
3    0.302918
Name: B, dtype: float64

In [111]:
dataframe[(dataframe['A']>0.5) & (dataframe['C'] > 0)]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

## Multi-Index and Index Hierarchy


In [112]:
layer1 = ['g1','g1','g1','g2','g2','g2']
layer2 = [1,2,3,1,2,3]
hier_index = list(zip(layer1,layer2))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [113]:
hier_index

MultiIndex(levels=[['g1', 'g2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [114]:
dataframe2 = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [115]:
dataframe2.loc['g1']

A         B
1  0.026761 -0.002614
2 -0.013075 -0.483993
3  0.615583  0.397851

In [116]:
dataframe2.loc['g1'].loc[1]

A    0.026761
B   -0.002614
Name: 1, dtype: float64


## Input and output


In [117]:
titanic = pd.read_csv('Datasets/titanic.csv')

In [118]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [119]:
titanic.drop('Name', axis=1 , inplace = True)

In [120]:
titanic.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [121]:
titanic.to_csv('Datasets/titanic_drop_names.csv')

** csv is one of the most important format but Pandas compatible with many other format like html table , sql, json and etc.**


## Mising data (NaN)

In [122]:
titanic.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [123]:
titanic.dropna()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch       Ticket  \
1              2         1       1  female  38.0      1      0     PC 17599   
3              4         1       1  female  35.0      1      0       113803   
6              7         0       1    male  54.0      0      0        17463   
10            11         1       3  female   4.0      1      1      PP 9549   
11            12         1       1  female  58.0      0      0       113783   
21            22         1       2    male  34.0      0      0       248698   
23            24         1       1    male  28.0      0      0       113788   
27            28         0       1    male  19.0      3      2        19950   
52            53         1       1  female  49.0      1      0     PC 17572   
54            55         0       1    male  65.0      0      1       113509   
62            63         0       1    male  45.0      1      0        36973   
66            67         1       2  female  29.0      0      0   C.A. 29395   
75            76         0       3    male  25.0      0      0       348123   
88            89         1       1  female  23.0      3      2        19950   
92            93         0       1    male  46.0      1      0  W.E.P. 5734   
96            97         0       1    male  71.0      0      0     PC 17754   
97            98         1       1    male  23.0      0      1     PC 17759   
102          103         0       1    male  21.0      0      1        35281   
110          111         0       1    male  47.0      0      0       110465   
118          119         0       1    male  24.0      0      1     PC 17558   
123          124         1       2  female  32.5      0      0        27267   
124          125         0       1    male  54.0      0      1        35281   
136          137         1       1  female  19.0      0      2        11752   
137          138         0       1    male  37.0      1      0       113803   
139          140         0       1    male  24.0      0      0     PC 17593   
148          149         0       2    male  36.5      0      2       230080   
151          152         1       1  female  22.0      1      0       113776   
170          171         0       1    male  61.0      0      0       111240   
174          175         0       1    male  56.0      0      0        17764   
177          178         0       1  female  50.0      0      0     PC 17595   
..           ...       ...     ...     ...   ...    ...    ...          ...   
737          738         1       1    male  35.0      0      0     PC 17755   
741          742         0       1    male  36.0      1      0        19877   
742          743         1       1  female  21.0      2      2     PC 17608   
745          746         0       1    male  70.0      1      1    WE/P 5735   
748          749         0       1    male  19.0      1      0       113773   
751          752         1       3    male   6.0      0      1       392096   
759          760         1       1  female  33.0      0      0       110152   
763          764         1       1  female  36.0      1      2       113760   
765          766         1       1  female  51.0      1      0        13502   
772          773         0       2  female  57.0      0      0  S.O./P.P. 3   
779          780         1       1  female  43.0      0      1        24160   
781          782         1       1  female  17.0      1      0        17474   
782          783         0       1    male  29.0      0      0       113501   
789          790         0       1    male  46.0      0      0     PC 17593   
796          797         1       1  female  49.0      0      0        17465   
802          803         1       1    male  11.0      1      2       113760   
806          807         0       1    male  39.0      0      0       112050   
809          810         1       1  female  33.0      1      0       113806   
820          821         1       1  female  52.0      1

In [124]:
titanic.dropna(axis=1)

PassengerId  Survived  Pclass     Sex  SibSp  Parch            Ticket  \
0              1         0       3    male      1      0         A/5 21171   
1              2         1       1  female      1      0          PC 17599   
2              3         1       3  female      0      0  STON/O2. 3101282   
3              4         1       1  female      1      0            113803   
4              5         0       3    male      0      0            373450   
5              6         0       3    male      0      0            330877   
6              7         0       1    male      0      0             17463   
7              8         0       3    male      3      1            349909   
8              9         1       3  female      0      2            347742   
9             10         1       2  female      1      0            237736   
10            11         1       3  female      1      1           PP 9549   
11            12         1       1  female      0      0            113783   
12            13         0       3    male      0      0         A/5. 2151   
13            14         0       3    male      1      5            347082   
14            15         0       3  female      0      0            350406   
15            16         1       2  female      0      0            248706   
16            17         0       3    male      4      1            382652   
17            18         1       2    male      0      0            244373   
18            19         0       3  female      1      0            345763   
19            20         1       3  female      0      0              2649   
20            21         0       2    male      0      0            239865   
21            22         1       2    male      0      0            248698   
22            23         1       3  female      0      0            330923   
23            24         1       1    male      0      0            113788   
24            25         0       3  female      3      1            349909   
25            26         1       3  female      1      5            347077   
26            27         0       3    male      0      0              2631   
27            28         0       1    male      3      2             19950   
28            29         1       3  female      0      0            330959   
29            30         0       3    male      0      0            349216   
..           ...       ...     ...     ...    ...    ...               ...   
861          862         0       2    male      1      0             28134   
862          863         1       1  female      0      0             17466   
863          864         0       3  female      8      2          CA. 2343   
864          865         0       2    male      0      0            233866   
865          866         1       2  female      0      0            236852   
866          867         1       2  female      1      0     SC/PARIS 2149   
867          868         0       1    male      0      0          PC 17590   
868          869         0       3    male      0      0            345777   
869          870         1       3    male      1      1            347742   
870          871         0       3    male      0      0            349248   
871          872         1       1  female      1      1             11751   
872          873         0       1    male      0      0               695   
873          874         0       3    male      0      0            345765   
874          875         1       2  female      1      0         P/PP 3381   
875          876         1       3  female      0      0              2667   
876          877         0       3    male      0      0              7534   
877          878         0       3    male      0      0            349212   
878          879         0       3    male      0      0            349217   
879          880         1       1  female      0      1             11767   
880          881         1 

In [126]:
titanic.fillna('Fill NaN').head()

PassengerId  Survived  Pclass     Sex Age  SibSp  Parch            Ticket  \
0            1         0       3    male  22      1      0         A/5 21171   
1            2         1       1  female  38      1      0          PC 17599   
2            3         1       3  female  26      0      0  STON/O2. 3101282   
3            4         1       1  female  35      1      0            113803   
4            5         0       3    male  35      0      0            373450   

      Fare     Cabin Embarked  
0   7.2500  Fill NaN        S  
1  71.2833       C85        C  
2   7.9250  Fill NaN        S  
3  53.1000      C123        S  
4   8.0500  Fill NaN        S

## Concating merging and ...

In [136]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [137]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [138]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [139]:
df3

A    B    C    D
2   A8   B8   C8   D8
3   A9   B9   C9   D9
4  A10  B10  C10  D10
5  A11  B11  C11  D11

**  Concatenation **

In [140]:
frames = [df1, df2, df3 ]

In [142]:
pd.concat(frames)
#pd.concat(frames, ignore_index=True)

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
4   A4   B4   C4   D4
5   A5   B5   C5   D5
6   A6   B6   C6   D6
7   A7   B7   C7   D7
2   A8   B8   C8   D8
3   A9   B9   C9   D9
4  A10  B10  C10  D10
5  A11  B11  C11  D11

In [143]:
pd.concat(frames, axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN   A8   B8   C8   D8
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN   A9   B9   C9   D9
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4  A10  B10  C10  D10
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5  A11  B11  C11  D11
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN

In [144]:
df1.append(df2)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

** Mergeing **

In [145]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [146]:
left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [147]:
right

C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3

In [148]:
pd.merge(left, right, on= 'key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [149]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [150]:
pd.merge(left, right, on=['key1', 'key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [152]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [153]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [154]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

A    B key1 key2   C   D
0   A0   B0   K0   K0  C0  D0
1   A2   B2   K1   K0  C1  D1
2   A2   B2   K1   K0  C2  D2
3  NaN  NaN   K2   K0  C3  D3

** Joining **

In [155]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [156]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [157]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [158]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2